# This is a basic workflow to help you get started with Actions

name: AutoProof

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ghcr.io/z3prover/z3:ubuntu-20.04-bare-z3-sha-1b5f7cd

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Download AutoProof distribution
        run:
          wget https://www.dropbox.com/s/1kibfwteo0fb96q/autoproof.tar.gz;
          tar xvf autoproof.tar.gz;
          sudo mv usr/local/Eiffel_21.11 /usr/local;

      - name: Install z3
        run:
          sudo apt-get install -y z3

      - name: Install .NET
        run:
          sudo apt-get install -y dotnet-runtime-6.0

      - name: Run AutoProof
        run:
          $ISE_EIFFEL/studio/spec/$ISE_PLATFORM/bin/ec_ap -config ap_project.ecf -verify collection:cluster
        env:
          ISE_EIFFEL: /usr/local/Eiffel_21.11
          ISE_PLATFORM: linux-x86-64


